# Changes here will be overwritten by Copier
_commit: 08e42af
_src_path: /Users/cjm/repos/monarch-project-copier
copyright_year: '2025'
email: my-name@my-org.org
full_name: My Name
gh_action_docs_preview: false
github_handle: linkmluser
github_org: linkml
license: Apache-2.0
project_description: Generic data browser static site builder
project_name: linkml-browser
project_slug: linkml_browser

