[project]
name = "linkml-browser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Mungall", email = "cjm@berkeleybop.org" }
]
requires-python = ">=3.12"
dependencies = [
    "linkml>=1.9.3",
    "linkml-store>=0.2.11",
    "typer>=0.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]

[project.scripts]
linkml-browser = "linkml_browser:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
